In [1]:
(1, 2, 3) * 3

(1, 2, 3, 1, 2, 3, 1, 2, 3)

# Numerical Python (Numpy)

In [6]:
import numpy as np

In [9]:
a = np.array([1, 2, 3])

In [10]:
a * 3

array([3, 6, 9])

# Math Functions

In [11]:
np.sum(a)

6

In [12]:
np.mean(a)

2.0

In [13]:
np.std(a)

0.816496580927726

In [14]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

# arange, linspace, logspace

In [15]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(0, 5, 2)

array([0, 2, 4])

In [17]:
np.arange("""shift + tab untuk melihat keterangan""")

TypeError: unsupported operand type(s) for -: 'str' and 'int'

In [18]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [19]:
np.linspace(0, 10, 2) #dipecah menjadi 2 bagian

array([ 0., 10.])

In [23]:
np.linspace(0, 10, 5) #dipecah menjadi 5 bagian

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
np.logspace(-3, 3, 7)

array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

# Random

In [25]:
np.random.rand(10)

array([0.33931268, 0.09909566, 0.07802982, 0.62761955, 0.13371832,
       0.70781449, 0.69580537, 0.32147499, 0.8491883 , 0.61913842])

In [29]:
np.random.rand(5,3)

array([[0.74737454, 0.61291763, 0.19915845],
       [0.81408118, 0.17091366, 0.47630007],
       [0.33550897, 0.51649973, 0.60589772],
       [0.50328503, 0.9973705 , 0.80976774],
       [0.85702591, 0.63663945, 0.38736375]])

# Control Randomness

In [31]:
#Random bilangan yang bisa dicontrol agar output tidak berubah
state = np.random.RandomState(42) #42 adalah tanda asteris pada asci maksudnya bebas, JOKES PROGRAMMER
state.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])